//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenEggVine.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoldenEggVine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;00&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;01&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;02&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;03&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;04&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;05&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;06&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;07&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;08&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;09&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0A&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0B&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0C&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0D&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0E&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0F&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;10&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;11&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;12&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;13&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;14&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;15&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;16&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;17&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;18&quot... ähnelt.
        /// </summary>
        internal static string BG1PalList {
            get {
                return ResourceManager.GetString("BG1PalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0&quot;,&quot;Cave 1&quot;,&quot;Crystals, Cave Plants, Cross-Section&quot;
        ///&quot;1&quot;,&quot;Forest 1&quot;,&quot;Palm Trees, Cross-Section&quot;
        ///&quot;2&quot;,&quot;Submarine Area&quot;,&quot;Rocks, Flowers, Logs, Water&quot;
        ///&quot;3&quot;,&quot;Pseudo 3D-Room&quot;,&quot;Moving Bricks, wavy Lava, Hookbill the Koopa&apos;s Room Stones&quot;
        ///&quot;4&quot;,&quot;Snow&quot;,&quot;Rocks, Ski Lifts, Conifers/Icy Water&quot;
        ///&quot;5&quot;,&quot;Jungle&quot;,&quot;Muddy Ground, Vines, Tree Covers, Jungle Rocks&quot;
        ///&quot;6&quot;,&quot;Castle 1&quot;,&quot;Brick Castle, Walls, Spikes, Destructible Blocks&quot;
        ///&quot;7&quot;,&quot;Grass 1&quot;,&quot;Bushes, Cross-Section&quot;
        ///&quot;8&quot;,&quot;Lava/Ice Cave&quot;,&quot;Lava, Icy Floor, Icicles, Crystals, Gia [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BG1TSList {
            get {
                return ResourceManager.GetString("BG1TSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;00&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;01&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;02&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;03&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;04&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;05&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;06&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;07&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;08&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;09&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0A&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0B&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0C&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0D&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0E&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0F&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;10&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;11&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;12&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;13&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;14&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;15&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;16&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;17&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;18&quot... ähnelt.
        /// </summary>
        internal static string BG2PalList {
            get {
                return ResourceManager.GetString("BG2PalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;00&quot;,&quot;Animated Waterfalls/Lavafalls&quot;,&quot;Waterfalls in Cave-themed Environment&quot;
        ///&quot;01&quot;,&quot;Bald Forest&quot;,&quot;Bals Forest Trees with Scrub underneath&quot;
        ///&quot;02&quot;,&quot;Submarine Area&quot;,&quot;Jungle Plants and underwater Rocks&quot;
        ///&quot;03&quot;,&quot;3D-Castle Bricks&quot;,&quot;Brick Background used in Pseudo-3D Rooms in Castles. Requires BG 1 Tileset 0x03&quot;
        ///&quot;04&quot;,&quot;Hills with Pine Forest&quot;,&quot;Huge Hills with a Pine Forest underneath and Grass on the bottom&quot;
        ///&quot;05&quot;,&quot;Pine Forest&quot;,&quot;Pine Forest with Clouds and Parallax Effects&quot;
        ///&quot;06&quot;,&quot;Animated Castle Waterfalls&quot;,&quot;Water [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BG2TSList {
            get {
                return ResourceManager.GetString("BG2TSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;00&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;01&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;02&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;03&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;04&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;05&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;06&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;07&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;08&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;09&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0A&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0B&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0C&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0D&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0E&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;0F&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;10&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;11&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;12&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;13&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;14&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;15&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;16&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;17&quot;,&quot;&quot;,&quot;&quot;
        ///&quot;18&quot... ähnelt.
        /// </summary>
        internal static string BG3PalList {
            get {
                return ResourceManager.GetString("BG3PalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;00&quot;,&quot;(Nothing)&quot;,&quot;When you don&apos;t want any BG3 effects&quot;
        ///&quot;01&quot;,&quot;Submarine Area Water&quot;,&quot;This is the graphics only, you still have to place the water&quot;
        ///&quot;02&quot;,&quot;BG3-using Sprites 1&quot;,&quot;Required for 0x036, 0x03F, 0x073, 0x0A5, 0x0DB&quot;
        ///&quot;03&quot;,&quot;Glitched Clouds&quot;,&quot;Do not use this&quot;
        ///&quot;04&quot;,&quot;Animated Smiley Clouds&quot;,&quot;Requires the correct BG3 Animation Tileset&quot;
        ///&quot;05&quot;,&quot;BG3-using Sprites 2&quot;,&quot;Required for 0x039, 0x057&quot;
        ///&quot;06&quot;,&quot;BG3-using Sprites 3&quot;,&quot;Required for 0x051&quot;
        ///&quot;07&quot;,&quot;BG3-using Sprites 4&quot;,&quot;Unused in the original Game&quot;
        ///&quot;08&quot;,&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BG3TSList {
            get {
                return ResourceManager.GetString("BG3TSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon EntitySelect {
            get {
                object obj = ResourceManager.GetObject("EntitySelect", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0&quot;,&quot;Nothing/Closes Door&quot;
        ///&quot;1&quot;,&quot;On Skis&quot;
        ///&quot;2&quot;,&quot;Rightward Pipe Exit&quot;
        ///&quot;3&quot;,&quot;Leftward Pipe Exit&quot;
        ///&quot;4&quot;,&quot;Downward Pipe Exit&quot;
        ///&quot;5&quot;,&quot;Upward Pipe Exit&quot;
        ///&quot;6&quot;,&quot;Walks Rightwards&quot;
        ///&quot;7&quot;,&quot;Walks Leftwards&quot;
        ///&quot;8&quot;,&quot;Goes Downwards&quot;
        ///&quot;9&quot;,&quot;Is Shot High&quot;
        ///&quot;A&quot;,&quot;Moonwards Shot&quot; ähnelt.
        /// </summary>
        internal static string ExitList {
            get {
                return ResourceManager.GetString("ExitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon HeaderEdit {
            get {
                object obj = ResourceManager.GetObject("HeaderEdit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;00&quot;,&quot;1-1 Room 1&quot;
        ///&quot;01&quot;,&quot;1-2 Room 1&quot;
        ///&quot;02&quot;,&quot;1-3 Room 1&quot;
        ///&quot;03&quot;,&quot;1-4 Room 1&quot;
        ///&quot;04&quot;,&quot;1-5 Room 1&quot;
        ///&quot;05&quot;,&quot;1-6 Room 1&quot;
        ///&quot;06&quot;,&quot;1-7 Room 1&quot;
        ///&quot;07&quot;,&quot;1-8 Room 3&quot;
        ///&quot;08&quot;,&quot;1-E Room 1&quot;
        ///&quot;09&quot;,&quot;2-1 Room 1&quot;
        ///&quot;0A&quot;,&quot;2-2 Room 1&quot;
        ///&quot;0B&quot;,&quot;2-3 Room 1&quot;
        ///&quot;0C&quot;,&quot;2-4 Room 1&quot;
        ///&quot;0D&quot;,&quot;2-5 Room 1&quot;
        ///&quot;0E&quot;,&quot;2-6 Room 1&quot;
        ///&quot;0F&quot;,&quot;2-7 Room 1&quot;
        ///&quot;10&quot;,&quot;2-8 Room 1&quot;
        ///&quot;11&quot;,&quot;2-E Room 1&quot;
        ///&quot;12&quot;,&quot;3-1 Room 1&quot;
        ///&quot;13&quot;,&quot;3-2 Room 1&quot;
        ///&quot;14&quot;,&quot;3-3 Room 1&quot;
        ///&quot;15&quot;,&quot;3-4 Room 1&quot;
        ///&quot;16&quot;,&quot;3-5 Room 1&quot;
        ///&quot;17&quot;,&quot;3-6 Room 1&quot;
        ///&quot;18&quot;,&quot;3-7 Room 1&quot;
        ///&quot;19&quot;,&quot;3-8 Room 1&quot;
        ///&quot;1... ähnelt.
        /// </summary>
        internal static string LevelList {
            get {
                return ResourceManager.GetString("LevelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0&quot;,&quot;Messages&quot;
        ///&quot;1&quot;,&quot;Cross-Section Cover&quot;
        ///&quot;2&quot;,&quot;Submarine Area, BG3 (transp.) &gt; BG1 &gt; BG2&quot;
        ///&quot;3&quot;,&quot;Fuzzies/Pseudo 3D-Room, No BG3, BG1 &gt; BG2&quot;
        ///&quot;4&quot;,&quot;(Unused)&quot;
        ///&quot;5&quot;,&quot;Messages, Pipes, BG3 &gt; BG1 &gt; BG2&quot;
        ///&quot;6&quot;,&quot;Rays of Light, Pipes, Messages&quot;
        ///&quot;7&quot;,&quot;Pipes, BG1 &gt; BG2&quot;
        ///&quot;8&quot;,&quot;Messages, BG3 (invisible) &gt; BG1 &gt; BG2&quot;
        ///&quot;9&quot;,&quot;Raphael the Raven&apos;s Moon&quot;
        ///&quot;A&quot;,&quot;Kamek&apos;s Room, BG1 &gt; BG2 &gt; BG3 &gt; BG4&quot;
        ///&quot;B&quot;,&quot;Pipes, BG1 &gt; BG2 &gt; BG3&quot;
        ///&quot;C&quot;,&quot;Messages, Pipes, No BG2, BG1 &gt; BG2&quot;
        ///&quot;D&quot;,&quot;Prince Froggy&apos;s Stomach&quot;
        ///&quot;E&quot;,&quot;Spotlight, BG3 (transp.)  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LevelModeList {
            get {
                return ResourceManager.GetString("LevelModeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon LevelMultiSave {
            get {
                object obj = ResourceManager.GetObject("LevelMultiSave", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon LevelPick {
            get {
                object obj = ResourceManager.GetObject("LevelPick", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon LevelSave {
            get {
                object obj = ResourceManager.GetObject("LevelSave", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0&quot;,&quot;Throwing Balloons (4 Buttons)&quot;
        ///&quot;1&quot;,&quot;Throwing Balloons (5 Buttons)&quot;
        ///&quot;2&quot;,&quot;Throwing Balloons (6 Buttons)&quot;
        ///&quot;3&quot;,&quot;(Freezes)&quot;
        ///&quot;4&quot;,&quot;Gather Coins&quot;
        ///&quot;5&quot;,&quot;Popping Balloons&quot;
        ///&quot;6&quot;,&quot;Popping Balloons (Platforms Move)&quot;
        ///&quot;7&quot;,&quot;(Freezes)&quot;
        ///&quot;8&quot;,&quot;(Freezes)&quot;
        ///&quot;9&quot;,&quot;Watermelon Seed Spitting Contest&quot; ähnelt.
        /// </summary>
        internal static string MinibattleList {
            get {
                return ResourceManager.GetString("MinibattleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon MiniMap {
            get {
                object obj = ResourceManager.GetObject("MiniMap", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0&quot;,&quot;Flower Garden&quot;,&quot;Mostly used for Levels with a warm, sunny atmosphere&quot;
        ///&quot;1&quot;,&quot;Jungle Theme&quot;,&quot;This theme fits all Jungle- and Submarine Levels&quot;
        ///&quot;2&quot;,&quot;Castle &amp; Fortress&quot;,&quot;Used in Castles or in dark, ominous places&quot;
        ///&quot;3&quot;,&quot;Room Before Boss (Before Mid-Boss)&quot;,&quot;This or Kamek&apos;s Theme is used in the Boss Room of a Mid-Boss&quot;
        ///&quot;4&quot;,&quot;Cave Theme&quot;,&quot;Used in Underground Levels. Fitting for Caves.&quot;
        ///&quot;5&quot;,&quot;Kamek&apos;s Theme (Before Mid-Boss)&quot;,&quot;This or Room Before Boss is used in the Boss Room of a Mid-Boss&quot;
        ///&quot;6&quot;,&quot;Bonus Game&quot;,&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MusicList {
            get {
                return ResourceManager.GetString("MusicList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon ObjectEdit {
            get {
                object obj = ResourceManager.GetObject("ObjectEdit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon PaletteEdit {
            get {
                object obj = ResourceManager.GetObject("PaletteEdit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon ScreenExitEdit {
            get {
                object obj = ResourceManager.GetObject("ScreenExitEdit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon SpriteEdit {
            get {
                object obj = ResourceManager.GetObject("SpriteEdit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;0&quot;,&quot;Icicles&quot;,&quot;Usually used for Icicles (Objects 0xA9, 0xAA, 0xAB, Sprite 0x190)&quot;
        ///&quot;1&quot;,&quot;(Unused)&quot;,&quot;Was not used in the game&quot;
        ///&quot;2&quot;,&quot;Submarine-Fish&quot;,&quot;Used for the Fish in Submarine Areas (Sprites 0xDF, 0xE0, 0xE1)&quot;
        ///&quot;3&quot;,&quot;Mousers, Pipe Cork&quot;,&quot;Used for Mousers and Pipe Corks (Sprites 0x30, 0x33, 0x1A3 and Sprite 0x1A4)&quot;
        ///&quot;4&quot;,&quot;Bowser&quot;,&quot;Used for Baby Bowser (Sprite 0x8E)&quot;
        ///&quot;5&quot;,&quot;(Unused)&quot;,&quot;Was not used in the game&quot;
        ///&quot;6&quot;,&quot;Golden Tap-Tap&quot;,&quot;Used for Tap-Tap the Golden (Sprite 0x3F)&quot;
        ///&quot;7&quot;,&quot;(Unused)&quot;,&quot;Was not used in t [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SprPalList {
            get {
                return ResourceManager.GetString("SprPalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
